# Generated by Django 5.2.8 on 2025-11-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.IntegerField()),
                ("ename", models.CharField(max_length=30)),
                ("esalr", models.FloatField()),
                ("eadd", models.CharField(max_length=30)),
                ("unm", models.CharField(max_length=30)),
                ("pw", models.CharField(max_length=30)),
            ],
        ),
    ]
